version: 1.0.{build}
skip_tags: true
stack: node 10, redis
skip_commits:
  message: /^chore(release)/
branches:
  only:
  - master
  - /preview\/*/ 
  - /release\/*/
image: 
- Ubuntu
- Visual Studio 2017
environment:
  GH_TOKEN: 
    secure: 0NJdORJRFjpB0dwUYv7bVNsbkldkoBhnvWik/CTOwAF/k9kP+/uTWMFnDcpEpt8E
  donetsdk: 3.0.100
init:
  - cmd: git config --global core.autocrlf true
install:
  - sh: wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
  - sh: sudo dpkg -i packages-microsoft-prod.deb
  - sh: sudo apt-get update
  - sh: sudo apt-get -y install apt-transport-https
  - sh: sudo chmod +x ./dotnet-install.sh
  - sh: sudo ./dotnet-install.sh -Channel Current -Version $donetsdk -InstallDir ./dotnetsdk -NoPath
  - sh: export PATH=/home/appveyor/projects/dymamicauthproviders/dotnetsdk:$PATH
  - sh: sudo apt -y install nuget
  - sh: nuget install GitVersion.CommandLine -ExcludeVersion
  - sh: mono GitVersion.CommandLine/tools/GitVersion.exe /l console /output buildserver
  - ps: if ($isWindows) { .\dotnet-install.ps1 -Version 3.0.100 }
  - cmd: nuget install redis-64 -excludeversion
  - cmd: redis-64\tools\redis-server.exe --service-install
  - cmd: redis-64\tools\redis-server.exe --service-start
  - cmd: gitversion /l console /output buildserver
  - cmd: nuget install ReportGenerator -ExcludeVersion
  - ps: ./appveyorinit.ps1
build_script:
  - ps: ./build.ps1
test_script:
  - cmd: publish.cmd
artifacts:
  - path: artifacts/**/*.nupkg
    name: nuget    
deploy:
  - provider: NuGet
    api_key:
      secure: S57o0WbfRlTkoQL26JackFN9GHt3L21yJWMgjRGMPuVMzdujY45mVehIHOs+arHH
    on:
      branch: 
      - /preview\/*/
      - /release\/*/
      CI_WINDOWS: true
  - provider: GitHub
    auth_token: $(GH_TOKEN)
    draft: true
    prerelease: true
    release: $(Version)
    on:
      branch: 
      - /preview\/*/
      CI_WINDOWS: true
for:
-
  branches:
    only:
      - master
  on_success:
    - cmd: git config --global credential.helper store 
    - ps: if ($isWindows) { Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n" }
    - cmd: IF EXIST coverage\docs ( git config --global user.email "aguacongas@gmail.com" )
    - cmd: IF EXIST coverage\docs ( git config --global user.name "Olivier Lefebvre" )
    - cmd: IF EXIST coverage\docs ( git stash )
    - cmd: IF EXIST coverage\docs ( git checkout gh-pages )
    - cmd: IF EXIST latest ( rmdir /S /Q latest )
    - cmd: IF EXIST coverage\docs ( move coverage\docs latest )
    - cmd: IF EXIST latest ( git add latest )
    - cmd: IF EXIST latest ( git commit latest -m "Appveyor build succed %APPVEYOR_BUILD_VERSION%" )
    - cmd: IF EXIST latest ( git push )
-
  branches:
    only:
      - /release\/*/
  on_success:
      - cmd: semantic-release -b %APPVEYOR_REPO_BRANCH%
      - cmd: git config --global credential.helper store
      - ps: if ($isWindows) { Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n" }
      - cmd: git config --global user.email "aguacongas@gmail.com"
      - cmd: git config --global user.name "Olivier Lefebvre"
      - cmd: git checkout gh-pages
      - cmd: git stash
      - cmd: mkdir %NextVersion%
      - cmd: move coverage\docs %NextVersion%
      - cmd: git add %NextVersion%
      - cmd: git commit %NextVersion% -m "Appveyor build succed %APPVEYOR_BUILD_VERSION%"
      - cmd: git push